# Site settings
title: Tech4Measurement
email: davclark@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
    Using sensor, mobile, and remote-sensing tech to measure social phenomena.
    Collecting the shared wisdom of psychology, development engineering, public
    policy, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tech4measurement.berkeley.edu" # the base hostname & protocol for your site
twitter_username: GlassBeadLabs
github_username: tech4measurement

# Build settings
markdown: kramdown
